from sqlalchemy import select
from .models import Document
from .session import SessionLocal


class PGVectorClient:
    """
    Client for performing CRUD and similarity searches on the Document table.
    """

    def __init__(self):
        """Initializes a new database session."""
        self.db = SessionLocal()

    def add_document(self, text, embedding):
        """
        Persists a new document and its vector embedding to the database.

        Args:
            text (str): The document content.
            embedding (list[float]): The vector array generated by an NLP model.
        """

        doc = Document(
            content=text,
            embedding=embedding
        )

        self.db.add(doc)
        self.db.commit()

    def similarity_search(self, query_embedding: list[float], k :int = 5) -> list[Document]:
        """
        Performs a K-Nearest Neighbors (KNN) search using Euclidean distance.

        Args:
            query_embedding (list[float]): The vector to compare against.
            k (int): Number of top results to return. Default is 5.

        Returns:
            list[Document]: The most similar document records.
        """
        # l2_distance represents the Euclidean distance between vectors.
        # Smaller distance = higher similarity.
        stmt = (
            select(Document)
            .order_by(Document.embedding.l2_distance(query_embedding))
            .limit(k)
        )

        results = self.db.execute(stmt).scalars().all()

        return results