import os
from uuid import uuid4
from dotenv import load_dotenv
from pydantic import BaseModel
from langchain.agents import create_agent
from langgraph.checkpoint.memory import InMemorySaver
from langchain.chat_models import init_chat_model
from app.utils import get_logger, cfg

# - load env variables
load_dotenv()
os.environ["MISTRAL_API_KEY"] = os.getenv("MISTRAL_API_KEY")
log = get_logger(__file__)


class AI_Agent:
    def __init__(self, name: str, model_name: str, system_prompt: str, tools: list = None, output_schema: BaseModel = None):
        """
        Initializes a unique agent instance with a specific model, system prompt, tools, and checkpointer.

        args:
            - name: A unique name for the agent instance.
            - model_name: The name of the model to be used by the agent.
            - system_prompt: The system prompt that guides the agent's behavior.
            - tools: A list of tools that the agent can utilize to perform tasks.
            - output_schema: The expected output schema for the agent's responses.
        exceptions:
            - Raises RuntimeError if there is an error during model loading or agent creation.  
        use:
            - This class can be instantiated to create multiple unique agents with different configurations, 
            allowing for concurrent interactions without interference.
        """
        self.name = name 
        self.system_prompt = system_prompt
        self.tools = tools
        self.checkpointer = InMemorySaver()
        self.output_schema = output_schema

        try:
            self.model = init_chat_model(model=model_name)
            log.info(f"[{self.name}] - Agent model loaded successfully.")
             
            self.agent_executor = create_agent(
                model = self.model,
                system_prompt = self.system_prompt,
                tools = self.tools,
                checkpointer = self.checkpointer,
                response_format = self.output_schema
            )
            log.info(f"[{self.name}] - Agent created successfully.")
        except Exception as e:
            log.error(f"[{self.name}] - Error during agent initialization: {str(e)}")
            raise RuntimeError(f"[{self.name}]- Error during agent initialization")


    def invoke(self, user_query: str, thread_id: str = None):
        """
        Invokes the agent with a user query and returns the response.

        args:
            - user_query: The query from the user to be processed by the agent.
            - thread_id: An optional unique identifier for the interaction thread, 
            **note**
            `
            used for maintaining context in conversations. if provided, the agent will use this thread_id to retrieve relevant context from previous interactions. 
            If not provided, a new thread_id will be generated for this interaction, meaning it will be treated
            `
        returns:
            - response: The response generated by the agent based on the user query.
        exceptions:
            - Raises RuntimeError if there is an error during agent invocation.
        use:
            - This method can be called to interact with the agent, 
            allowing for concurrent interactions by using unique thread IDs.
        """

        if not thread_id:
            log.warning(f"[{self.name}] - No thread_id provided and generating new one.")
            thread_id = str(uuid4())

        try:
            response = self.agent_executor.invoke(
                {
                    "messages": [{
                        "role": "user",
                        "content": user_query
                    }],
                },
                {"configurable": {"thread_id": thread_id}},
            )
            log.info(f"[{self.name}] - Response generated successfully for thread_id: {thread_id}")
            return response
        except Exception as e:
            log.error(f"[{self.name}] - Error during agent invocation: {str(e)}")
            raise RuntimeError(f"[{self.name}] - Error during agent invocation")


