
POSTGRES_USER : myuser  
POSTGRES_PASSWORD : myuserpassword  
POSTGRES_HOST : localhost #pdb #gvector_db  
POSTGRES_PORT : 5432  
POSTGRES_DB : langchain  
COLLECTION_NAME: my_collection
TABLE_NAME : documents  
VECTOR_SIZE : 1024  