from app.utils import cfg

POSTGRES_USER = cfg.db.POSTGRES_USER
POSTGRES_PASSWORD = cfg.db.POSTGRES_PASSWORD
POSTGRES_HOST = cfg.db.POSTGRES_HOST  
POSTGRES_PORT = cfg.db.POSTGRES_PORT
POSTGRES_DB = cfg.db.POSTGRES_DB
COLLECTION_NAME = cfg.db.COLLECTION_NAME

DATABASE_URL = f"postgresql+psycopg://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"
